# Generated by Django 3.2.3 on 2021-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogtitle',
            field=models.CharField(default=12321, max_length=60),
            preserve_default=False,
        ),
    ]
