# Generated by Django 3.2.3 on 2021-05-22 03:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_blog_blogtitle'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('filtertime', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogtime',
            field=models.DateField(auto_now=True),
        ),
    ]
