# Generated by Django 3.2.3 on 2021-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20210529_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userProfile',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
