# Generated by Django 3.2.3 on 2021-05-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_userprofile_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userProfile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
