# Generated by Django 3.2.3 on 2021-05-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='images/'),
        ),
    ]
