# Generated by Django 3.2.3 on 2021-05-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_alter_userprofile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, default='media/default_profile.jpg', null=True, upload_to='images/'),
        ),
    ]
