# Generated by Django 3.2.3 on 2021-06-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
