# Generated by Django 3.2.3 on 2021-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_alter_userprofile_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profileGallery',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='images/'),
        ),
    ]
