# Generated by Django 3.2.3 on 2021-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_auto_20210604_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileGallery',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
