# Generated by Django 3.2.3 on 2021-06-04 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0023_alter_userprofile_profilegallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profileGallery',
        ),
        migrations.CreateModel(
            name='ProfileGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGallery', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
