# Generated by Django 3.2.3 on 2021-06-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
