# Generated by Django 3.2.3 on 2021-06-25 11:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_alter_blog_blog_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('date_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
