# Generated by Django 3.2.3 on 2021-06-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_alter_blog_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogtime',
            field=models.DateTimeField(),
        ),
    ]
