# Generated by Django 3.2.3 on 2021-06-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_auto_20210625_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
