# Generated by Django 3.2.3 on 2021-06-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_alter_blog_blogtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
